version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: registry.gitlab.com/rayriffy/rayriffy-com/composer-yarn:latest
        auth:
          username: $REGISTRY_USER
          password: $REGISTRY_PASS
        environment:
          DEPLOY_HOST: $DEPLOY_HOST
          DEPLOY_COMMAND: $DEPLOY_COMMAND
      # - image: mysql:5.7
      #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      #   environment:
      #     MYSQL_USER: homestead
      #     MYSQL_PASSWORD: secret
      #     MYSQL_DATABASE: homestead
      #     MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - run:
          name: Install required packages & Configuration
          command: |
            apk update && apk add alpine-sdk
      - run:
          name: Config .env file
          command: |
            cp .env.example .env
      - run:
          name: Manage Composer Packages
          command: |
            composer install
      - run:
          name: Generate Key
          command: |
            php artisan key:generate
      # - run:
      #     name: Migrate Database
      #     command: |
      #       php artisan migrate --force
  deploy:
    machine:
        enabled: true
    working_directory: ~/workspace
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:64:ff:ff:10:61:8f:f5:22:9a:60:d7:f9:d9:62:93"
      - run:
          name: Get rayriffy-com repo
          command: |
            git clone git@gitlab.com:rayriffy/rayriffy-com.git
            cd rayriffy-com/web/data/html
            mkdir ~/tmp
            mv booking.ivaothai.com/.env ~/tmp/.env
            rm -rf booking.ivaothai.com
      - run:
          name: Get Code
          command: |
            cd rayriffy-com/web/data/html
            git clone git@github.com:rayriffy/ivaothai-booking-api.git booking.ivaothai.com
            cd booking.ivaothai.com
            git checkout release
      - run:
          name: Remove Git folder
          command: |
            cd rayriffy-com/web/data/html/booking.ivaothai.com
            ls -l -a
            rm -rf .git/
            rm -rf .gitignore
            rm -rf .circleci/
            mv ~/tmp/.env ./.env
      - run:
          name: Push
          command: |
            cd rayriffy-com/web/data/html/booking.ivaothai.com
            git config --global user.name "Autobot"
            git config --global user.email bot@rayriffy.com
            git add .
            git commit -m "[AUTO] booking.ivaothai.com Deploy Triggered"
            git push origin master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release